import type { TShortcut } from "./types";

export const SHORTCUTS: TShortcut[] = [
  { keys: ["Tab"], action: "Focus task (yellow border)" },
  { keys: ["Shift", "Tab"], action: "Focus prev (yellow border)" },
  { keys: ["Space"], action: "Lift or drop task" },
  { keys: ["🡹", "🡻", "🡸", "🡺"], action: "Move task" },
  { keys: ["Esc"], action: "Cancel drag" },
  { keys: ["Enter"], action: "Edit task" },
  { keys: ["Ctrl / ⌘", "J"], action: "New column" },
  { keys: ["Ctrl / ⌘", "🡹"], action: "Expand all columns" },
  { keys: ["Ctrl / ⌘", "🡻"], action: "Collapse all columns" },
];

export const ADJECTIVES: string[] = [
  "vibrant",
  "cosmic",
  "silent",
  "rapid",
  "golden",
  "frozen",
  "hidden",
  "fierce",
  "lucid",
  "nimble",
  "azure",
  "crimson",
  "stellar",
  "phantom",
  "primal",
  "radiant",
  "spectral",
  "ethereal",
  "obsidian",
  "kinetic",
  "mystic",
  "ancient",
  "swift",
  "galactic",
  "emerald",
  "serene",
  "bold",
  "wild",
  "lunar",
  "solar",
  "infinite",
  "vivid",
  "electric",
  "brazen",
  "noble",
  "loyal",
  "neon",
  "velvet",
  "iron",
  "silver",
  "dark",
  "light",
  "brave",
  "calm",
  "stormy",
  "enigmatic",
  "majestic",
  "lush",
  "brisk",
  "frosty",
];

export const NOUNS: string[] = [
  "nebula",
  "falcon",
  "aurora",
  "summit",
  "cipher",
  "vortex",
  "horizon",
  "tempest",
  "beacon",
  "quartz",
  "zenith",
  "cascade",
  "ember",
  "orchid",
  "drift",
  "pulse",
  "stream",
  "echo",
  "shadow",
  "flame",
  "spark",
  "stone",
  "tide",
  "wave",
  "wind",
  "frost",
  "bloom",
  "peak",
  "valley",
  "glacier",
  "phoenix",
  "dragon",
  "wolf",
  "tiger",
  "comet",
  "meteor",
  "planet",
  "galaxy",
  "orbit",
  "prism",
  "crystal",
  "sphere",
  "matrix",
  "nexus",
  "portal",
  "rift",
  "spire",
  "crag",
  "dune",
  "monolith",
];
